# Generated by Django 4.2.9 on 2024-02-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollaborateRequest',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lname',
            new_name='last_name',
        ),
    ]
