# Generated by Django 4.2.9 on 2024-02-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
    ]
