# Generated by Django 4.2.9 on 2024-01-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
