# Generated by Django 4.2.9 on 2024-01-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_board', '0002_query_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
