# Generated by Django 4.2.9 on 2024-01-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_board', '0004_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['-created_on']},
        ),
    ]
