# Generated by Django 4.2.9 on 2024-01-31 18:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_board', '0005_alter_answer_options_alter_query_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
