# Generated by Django 4.2.9 on 2024-02-12 17:09

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_board', '0007_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='category',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='query',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='query_category', to='help_board.category'),
            preserve_default=False,
        ),
    ]
