# Generated by Django 4.2.9 on 2024-02-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_board', '0008_remove_query_featured_image_category_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='query',
            name='excerpt',
        ),
    ]
