# Generated by Django 4.2.9 on 2024-02-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_board', '0010_rename_query_answer_answer_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='category',
            name='fontawesome_icon',
            field=models.CharField(default='a'),
            preserve_default=False,
        ),
    ]
