# Generated by Django 4.2.9 on 2024-02-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_board', '0011_remove_category_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='updated_on',
        ),
    ]
